// src/features/patient/services/checkInPdfService.ts

import * as Print from "expo-print";

/**
 * Generate a PDF for front-desk / clinic check-in.
 * Caller passes the same object used for FHIR:
 * {
 *   firstName, lastName, dob, phone, email,
 *   emergencyName, emergencyPhone,
 *   pharmacyName, pharmacyAddress,
 *   insuranceProvider, memberId, insuranceCardUri
 * }
 */
export async function generateCheckInPDF(checkInData: any): Promise<string> {
  const {
    firstName,
    lastName,
    dob,
    phone,
    email,

    emergencyName,
    emergencyPhone,

    pharmacyName,
    pharmacyAddress,

    insuranceProvider,
    memberId,
    insuranceCardUri,
  } = checkInData || {};

  const fullName =
    [firstName, lastName].filter((p) => typeof p === "string" && p.length > 0).join(" ") ||
    "—";

  // Simple helper so we don't render "undefined"
  const safe = (value: any) => (value == null || value === "" ? "—" : String(value));

  const insuranceCardImg = insuranceCardUri
    ? `<div style="margin-top: 8px;">
         <div style="font-size: 11px; color: #555; margin-bottom: 4px;">Insurance Card</div>
         <img src="${insuranceCardUri}" style="max-width: 220px; border-radius: 8px; border: 1px solid #eee;" />
       </div>`
    : "";

  const html = `
    <html>
      <head>
        <meta charset="utf-8" />
        <style>
          * {
            box-sizing: border-box;
          }
          body {
            font-family: -apple-system, BlinkMacSystemFont, "SF Pro Text",
              system-ui, Helvetica, Arial, sans-serif;
            margin: 0;
            padding: 24px;
            background-color: #f4f5f7;
            color: #111827;
          }
          h1 {
            font-size: 22px;
            margin: 0 0 4px 0;
          }
          .subtitle {
            font-size: 12px;
            color: #6b7280;
            margin-bottom: 20px;
          }
          .card {
            background-color: #ffffff;
            border-radius: 16px;
            padding: 16px 18px;
            margin-bottom: 12px;
            box-shadow: 0 6px 18px rgba(15, 23, 42, 0.06);
          }
          .card-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 8px;
          }
          .card-title {
            font-size: 14px;
            font-weight: 600;
            color: #111827;
          }
          .badge {
            font-size: 10px;
            padding: 3px 8px;
            border-radius: 999px;
            background-color: #eff6ff;
            color: #1d4ed8;
          }
          .row {
            font-size: 12px;
            margin: 2px 0;
            display: flex;
          }
          .label {
            width: 110px;
            color: #6b7280;
          }
          .value {
            flex: 1;
            color: #111827;
          }
          .section-spacer {
            height: 4px;
          }
        </style>
      </head>
      <body>
        <h1>Check-In Summary</h1>
        <div class="subtitle">Generated by MyHealthVaultAI</div>

        <!-- Patient Identity -->
        <div class="card">
          <div class="card-header">
            <div class="card-title">Patient Identity</div>
            <div class="badge">Required</div>
          </div>
          <div class="row">
            <div class="label">Name</div>
            <div class="value">${fullName}</div>
          </div>
          <div class="row">
            <div class="label">Date of Birth</div>
            <div class="value">${safe(dob)}</div>
          </div>
          <div class="row">
            <div class="label">Phone</div>
            <div class="value">${safe(phone)}</div>
          </div>
          <div class="row">
            <div class="label">Email</div>
            <div class="value">${safe(email)}</div>
          </div>
        </div>

        <!-- Emergency Contact -->
        <div class="card">
          <div class="card-header">
            <div class="card-title">Emergency Contact</div>
            <div class="badge">Optional</div>
          </div>
          <div class="row">
            <div class="label">Name</div>
            <div class="value">${safe(emergencyName)}</div>
          </div>
          <div class="row">
            <div class="label">Phone</div>
            <div class="value">${safe(emergencyPhone)}</div>
          </div>
        </div>

        <!-- Pharmacy -->
        <div class="card">
          <div class="card-header">
            <div class="card-title">Preferred Pharmacy</div>
            <div class="badge">Optional</div>
          </div>
          <div class="row">
            <div class="label">Name</div>
            <div class="value">${safe(pharmacyName)}</div>
          </div>
          <div class="row">
            <div class="label">Address</div>
            <div class="value">${safe(pharmacyAddress)}</div>
          </div>
        </div>

        <!-- Insurance -->
        <div class="card">
          <div class="card-header">
            <div class="card-title">Insurance</div>
            <div class="badge">Required</div>
          </div>
          <div class="row">
            <div class="label">Provider</div>
            <div class="value">${safe(insuranceProvider)}</div>
          </div>
          <div class="row">
            <div class="label">Member ID</div>
            <div class="value">${safe(memberId)}</div>
          </div>
          ${insuranceCardImg}
        </div>
      </body>
    </html>
  `;

  const result = await Print.printToFileAsync({ html });

  // returns local file URI, e.g. "file:///..."
  return result.uri;
}
